
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace taske2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class applied_post
{

    public int Id { get; set; }



    public virtual Person Person { get; set; }

    public virtual internship_post internship_post { get; set; }

}

}
