
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace taske2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class internship_post
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public internship_post()
    {

        this.applied_post = new HashSet<applied_post>();

    }


    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Post_time { get; set; }

    public string End_time { get; set; }



    public virtual UserPassword UserPassword { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<applied_post> applied_post { get; set; }

}

}
