

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace taske2.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class resumerdatabaseEntities : DbContext
{
    public resumerdatabaseEntities()
        : base("name=resumerdatabaseEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Certification> Certifications { get; set; }

    public virtual DbSet<Education> Educations { get; set; }

    public virtual DbSet<Language> Languages { get; set; }

    public virtual DbSet<Person> People { get; set; }

    public virtual DbSet<Skill> Skills { get; set; }

    public virtual DbSet<WorkExperience> WorkExperiences { get; set; }

    public virtual DbSet<UserPassword> UserPassword { get; set; }

    public virtual DbSet<internship_post> internship_post { get; set; }

    public virtual DbSet<applied_post> applied_post { get; set; }

    public virtual DbSet<Table> Table { get; set; }

}

}

