
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace taske2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class WorkExperience
{

    public int IDexperience { get; set; }

    public string Company { get; set; }

    public string Title { get; set; }

    public string Country { get; set; }

    public string FromYear { get; set; }

    public string ToYear { get; set; }

    public string Description { get; set; }

    public Nullable<int> IDPerson { get; set; }



    public virtual Person Person { get; set; }

}

}
